before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}-{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

aurs:
  - name: secure-keepass-fuse-bin
    homepage: "https://github.com/Split174/secure-keepass-fuse"
    description: "Mounts attachments as fuse-filesystem (Binary)"
    maintainers:
      - "Split174 <no-reply@aur.archlinux.org>"
    license: "MIT"
    git_url: "ssh://aur@aur.archlinux.org/secure-keepass-fuse-bin.git"
    private_key: '{{ .Env.AUR_KEY }}'
    commit_author:
      name: "goreleaserbot"
      email: "bot@goreleaser.com"
    depends:
      - "fuse3"
      - "zenity"
    provides:
      - "secure-keepass-fuse"
    conflicts:
      - "secure-keepass-fuse"
    package: install -Dm755 "${pkgname}_${pkgver}_${CARCH}.binary" "${pkgdir}/usr/bin/secure-keepass-fuse"